version: '3.9'
services:
  webapp:
    build:
      args:
        - PIP_VERSION=${WEBAPP_PIP_VERSION:-23.}
        - POETRY_VERSION=${WEBAPP_POETRY_VERSION:-1.4.2}
        - PYTHON_VERSION=${WEBAPP_PYTHON_VERSION:-3.10.9}
        - VERSION=${WEBAPP_VERSION:-dev}
      context: services/webapp/
    container_name: webapp.getexchrate
    depends_on:
      - db
    entrypoint: [ task, run-server-prod ]
    environment:
      DATABASE_URL: postgresql://getexchrate:getexchrate@db:5432/getexchrate
      MODE_DEBUG: 1
      PORT: 80
      TEST_SERVICE_URL: http://webapp:80
    image: webapp.getexchrate:${WEBAPP_VERSION:-dev}
    networks:
      - getexchrate
    ports:
      - "8000:80"
    tmpfs:
      - /app/.local/:mode=777,size=10m,uid=1000,gid=1000
    volumes:
      - ./services/webapp/:/app/:ro
  db:
    build:
      context: services/db/
      args:
        - VERSION=${DB_VERSION:-dev}
    container_name: db.getexchrate
    environment:
      POSTGRES_USER: getexchrate
      POSTGRES_PASSWORD: getexchrate
      POSTGRES_DB: getexchrate
    image: db.getexchrate:${DB_VERSION:-dev}
    ports:
      - "5432:5432"
    networks:
      - getexchrate
    volumes:
      - ./.local/services/db/data/:/var/lib/postgresql/data:rw
  dba:
    build:
      context: services/dba/
    container_name: dba.getexchrate
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: getexchrate@getexchrate.dev
      PGADMIN_DEFAULT_PASSWORD: getexchrate
    image: dba.getexchrate:dev
    ports:
      - "8801:80"
    networks:
      - getexchrate
networks:
  getexchrate:
    name: getexchrate.net
    driver: bridge
