version: '3.9'
services:
  webapp:
    build:
      args:
        - PIP_VERSION=${WEBAPP_PIP_VERSION}
        - POETRY_VERSION=${WEBAPP_POETRY_VERSION}
        - PYTHON_VERSION=${WEBAPP_PYTHON_VERSION}
        - VERSION=${WEBAPP_VERSION}
      context: services/webapp/
    container_name: webapp.getexchrate
    depends_on:
      - db
    entrypoint: [ task, run-server-prod ]
    environment:
      DATABASE_URL: ${WEBAPP_DATABASE_URL}
      MODE_DEBUG: ${WEBAPP_MODE_DEBUG}
      PORT: ${WEBAPP_PORT}
      TEST_SERVICE_URL: ${WEBAPP_TEST_SERVICE_URL}
    image: webapp.getexchrate:${WEBAPP_VERSION}
    networks:
      - getexchrate
    ports:
      - "8000:80"
    tmpfs:
      - /app/.local/:mode=777,size=10m,uid=9999,gid=9999
    volumes:
      - ./services/webapp/:/app/:ro
  db:
    build:
      context: services/db/
      args:
        - VERSION=${DB_VERSION}
    container_name: db.getexchrate
    environment:
      POSTGRES_USER: getexchrate
      POSTGRES_PASSWORD: getexchrate
      POSTGRES_DB: getexchrate
    image: db.getexchrate:${DB_VERSION}
    ports:
      - "5432:5432"
    networks:
      - getexchrate
    volumes:
      - ./.local/services/db/data/:/var/lib/postgresql/data:rw
  dba:
    build:
      context: services/dba/
    container_name: dba.getexchrate
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: getexchrate@getexchrate.dev
      PGADMIN_DEFAULT_PASSWORD: getexchrate
    image: dba.getexchrate:dev
    ports:
      - "8801:80"
    networks:
      - getexchrate
networks:
  getexchrate:
    name: getexchrate.net
    driver: bridge
